; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pro8MHzatmega328]
platform = atmelavr
board = pro8MHzatmega328
framework = arduino
extra_scripts = scripts/custom_targets.py
test_framework = unity
test_ignore = host
monitor_filters = send_on_enter
monitor_echo = yes
# Set this to make the "Test: Host Protocol Smoke" sidebar target know which serial port to use.
; monitor_port = /dev/ttyUSB0
check_skip_packages = true
lib_deps = 
	poelstra/MultiButton@^1.2.0
	adafruit/Adafruit PCD8544 Nokia 5110 LCD library@^2.0.3

[env:native]
platform = native
extra_scripts = scripts/custom_targets.py
test_framework = unity
test_ignore = host
build_flags =
	-Isrc
